module.exports = [
    "Don't you open up that {{ adjective }} {{ noun }}",
    "Don't you let out that {{ noun }}",
    "Poppin' {{ nouns }} is all {{ nouns }} know",
    "In the {{ noun }} is all {{ nouns }} know ({{ noun }}!)",
    "Don't go through the {{ noun }} (Through the {{ noun }}!)",
    "It's {{ adjective }} at the {{ noun }}",
    "So don't you open up that {{ noun }}",
    "Don't you let out that {{ adjective }} {{ noun }}",
    "You getting {{ adjective }}, I'm getting {{ adjective }}",
    "They say that I'm {{ adjective }}, I used to talk to {{ a_noun }}",
    "What's {{ a_noun }} to {{ a_noun }}? What's {{ a_noun }} to {{ a_noun }}?",
    "Got my {{ nouns }} in {{ noun }}, and they going {{ nouns }}",
    "{{ adjective }} {{ noun }} lie to {{ an_adjective }} {{ noun }}, that's just some {{ noun }} that {{ noun }} don't do",
    "If {{ adjective }} Metro don't trust {{ noun }} I'ma shoot ya",
    "Jumpman jumpman jumpman them {{ nouns }} up to something",
    "Cause I got a really {{ adjective }} {{ noun }}, {{ noun }} need some really {{ adjective }} {{ nouns }}"
    "I'm drinkin' {{ noun }}, it help me sleep",
    "{{ noun }} used to call me on my {{ noun }}, late night when {{ noun }} need my {{ noun }}",
    "Ever since {{ noun }} left the {{ noun }} you got {{ a_noun }} for yourself now"
    "{{ noun }} was born with some {{ adjective }} {{ noun }}, drinkin' {{ noun }} out {{ a_noun }}",
    "I'm sprayin' at these {{ adjective }} {{ nouns }} like {{ noun }}",
    "My President is {{ adjective }}, my {{ noun }} too",
    "Live through the {{ noun }}, life's {{ an_adjective} hustle",
    "{{ noun }} caught {{ a_noun }} about a week ago",
    "I got {{ nouns }} askin' me about the {{ noun }} for the {{ noun }}",
    "{{ adjective }} English, 800 {{ nouns }} of {{ noun }}",
    "Did a lot of {{ noun }} just to live this here {{ noun }}",
    "Started from the {{ noun }}, now {{ noun }} here"
    "I got my {{ nouns }} on you, you're everything that I see",
    "Call me Fred Flinstone cause {{ noun }} can make your {{ noun }} rock",
    "Dontcha wish your {{ noun }} was {{ adjective }} like {{ noun }}?",
    "{{ noun }} the way you movin, got me in {{ a_noun }}",
    "You wanna see some {{ noun }}? I wanna see some {{ noun }}",
    "Now watch me {{ noun }} that {{ noun }}",
    "Watch me {{ noun }}, now watch me {{ noun }}",
    "{{ adjective }} {{ noun }} gone give it to ya",
    "Pour some {{ noun }} on {{ noun }}",
    "You got the {{ nouns }} like Jagger"
];
