module.exports = [
    "Don't you open up that {{ adjective }} {{ noun }}",
    "Don't you let out that {{ noun }}",
    "In the {{ noun }} is all {{ nouns }} know ({{ noun }}!)",
    "Don't go through the {{ noun }} (Through the {{ noun }}!)",
    "It's {{ adjective }} at the {{ noun }}",
    "So don't you open up that {{ noun }}",
    "Don't you let out that {{ adjective }} {{ noun }}",
    "You getting {{ adjective }}, I'm getting {{ adjective }}",
    "They say that I'm {{ adjective }}, I used to talk to {{ a_noun }}",
    "What's {{ a_noun }} to {{ a_noun }}? What's {{ a_noun }} to {{ a_noun }}?",
    "Got my {{ nouns }} in {{ noun }}, and they going {{ nouns }}",
    "{{ adjective }} {{ noun }} lie to {{ an_adjective }} {{ noun }}, that's just some {{ noun }} that {{ noun }} don't do",
    "{{ noun }} {{ noun }} {{  noun }} them {{ nouns }} up to something",
    "Cause I got a really {{ adjective }} {{ noun }}, {{ noun }} need some really {{ adjective }} {{ nouns }}",
    "{{ noun }} used to call me on my {{ noun }}, {{ adjective }} {{ noun }} when {{ noun }} need my {{ noun }}",
    "Ever since {{ noun }} left the {{ noun }} you got {{ a_noun }} for yourself now",
    "{{ noun }} was born with some {{ adjective }} {{ noun }}, drinkin' {{ noun }} out {{ a_noun }}",
    "My {{ noun }} is {{ adjective }}, my {{ noun }} too",
    "Live through the {{ noun }}, life's {{ an_adjective }} hustle",
    "{{ noun }} caught {{ a_noun }} about a week ago",
    "I got {{ nouns }} askin' me about the {{ noun }} for the {{ noun }}",
    "Did a lot of {{ noun }} just to live this here {{ noun }}",
    "Started from the {{ noun }}, now {{ noun }} here",
    "I got my {{ nouns }} on you, you're everything that I see",
    "Dontcha wish your {{ noun }} was {{ adjective }} like {{ noun }}?",
    "{{ noun }} the way you movin, got me in {{ a_noun }}",
    "You wanna see some {{ noun }}? I wanna see some {{ noun }}",
    "Now watch me {{ noun }} that {{ noun }}",
    "Watch me {{ noun }}, now watch me {{ noun }}",
    "{{ an_adjective }} {{ noun }} looking at me",
    "{{ an_adjective }} {{ noun }}",
    "{{ a_adjective }} {{ noun }}",
    "I am a {{ noun }}, hurry up with my {{ noun }}",
    "{{ adjective }} {{ noun }} gone give it to ya",
    "Pour some {{ noun }} on {{ noun }}",
    "You got the {{ nouns }} like {{ noun }}",
    "I'm {{ adjective }} and I know it",
    "Maybe I'm going {{ adjective }}, maybe I'm going {{ adjective }}",
    "I be in the {{ noun }} cooking {{ nouns }} with my {{ noun }}, yeah",
    "I ain't got no {{ noun }}, {{ adjective }} {{ nouns }} is the only {{ noun }} that I like ",
    "I just bought {{ a_noun }}, three {{ nouns }}, that {{ noun }} {{ a_noun }}",
    "Listen up {{ nouns }}, cause {{ noun }} is it",
    "I ain't {{ adjective }}, I ain't {{ adjective }}",
    "{{ nouns }} just come and go like {{ nouns }}",
    "What you gonna do with all that {{ noun }}, all that {{ noun }} up in your {{ noun }}?",
    "Cause I ain't no {{ adjective }} {{ noun }}",
    "{{ adjective }} {{ noun }} so {{ adjective }}, we'll melt your {{ noun }}",
    "{{ noun }} make me feel like I'm livin' {{ an_adjective }} {{ noun }}",
    "You're {{ adjective }} then you're {{ adjective }}, you're yes then you're no",
    "I'm all about that {{ noun }}, about that {{ noun }}, no {{ noun }}",
    "She wears {{ adjective }} {{ nouns }}, I wear {{ adjective }} {{ nouns }}",
    "She's {{ noun }} captain and I'm on the {{ nouns }}",
    "I don't like your {{ adjective }}, I think you need {{ an_adjective }} {{ noun }}",
    "He was {{ a_noun }}, she was {{ a_noun }}, can I make it any more {{ adjective }}?",
    "And I know she'll be the {{ noun }} of {{ noun }}, at least we'll both be {{ adjective }}",
    "I can't feel my {{ noun }} when I'm with {{ noun }}",
    "I think I found myself {{ a_noun }}, she's always {{ adjective }} when I need {{ a_noun }}",
    "Give it to {{ noun }}, I'm {{ adjective }}",
    "{{ noun }} is a {{ noun }}",
    "I like your {{ noun }}",
    "Call me {{ noun }}",
    "Straight outta {{ noun }}",
    "No I do not have a {{ noun }}",
    "The {{ noun }}, the {{ noun }}, the {{ noun }}",
    "Baby be the {{ adjective }} {{ noun }}",
    "I'll be the {{ adjective }} {{ noun }}",
    "Chasing {{ adjective }} {{ nouns }}, I'm {{ a_noun }}",
    "Hey now, you're {{ a_adjective }} {{ noun }}",
    "Get your {{ noun }} on!",
    "I go {{ adjective }} in the {{ noun }}",
    "Hello {{ noun }}, my {{ adjective }} {{ noun }}",
    "I see {{ nouns }} {{ ajective }}",
    "{{ adjective }} {{ nouns }} too"
];
