module.exports = [
    "Don't you open up that {{ adjective }} {{ noun }}",
    "Don't you let out that {{ noun }}",
    "Poppin' {{ nouns }} is all {{ nouns }} know",
    "In the {{ noun }} is all {{ nouns }} know ({{ noun }}!)",
    "Don't go through the {{ noun }} (Through the {{ noun }}!)",
    "It's {{ adjective }} at the {{ noun }}",
    "So don't you open up that {{ noun }}",
    "Don't you let out that {{ adjective }} {{ noun }}",
    "You getting {{ adjective }}, I'm getting {{ adjective }}",
    "They say that I'm {{ adjective }}, I used to talk to {{ a_noun }}",
    "What's {{ a_noun }} to {{ a_noun }}? What's {{ a_noun }} to {{ a_noun }}?",
    "Got my {{ nouns }} in {{ noun }}, and they going {{ nouns }}",
    "{{ adjective }} {{ noun }} lie to {{ an_adjective }} {{ noun }}, that's just some {{ noun }} that {{ noun }} don't do",
    "If {{ adjective }} Metro don't trust {{ noun }} I'ma shoot ya",
    "Jumpman jumpman jumpman them {{ nouns }} up to something",
    "Cause I got a really {{ adjective }} {{ noun }}, {{ noun }} need some really {{ adjective }} {{ nouns }}",
    "I'm drinkin' {{ noun }}, it help me sleep",
    "{{ noun }} used to call me on my {{ noun }}, late night when {{ noun }} need my {{ noun }}",
    "Ever since {{ noun }} left the {{ noun }} you got {{ a_noun }} for yourself now",
    "{{ noun }} was born with some {{ adjective }} {{ noun }}, drinkin' {{ noun }} out {{ a_noun }}",
    "I'm sprayin' at these {{ adjective }} {{ nouns }} like {{ noun }}",
    "My President is {{ adjective }}, my {{ noun }} too",
    "Live through the {{ noun }}, life's {{ an_adjective }} hustle",
    "{{ noun }} caught {{ a_noun }} about a week ago",
    "I got {{ nouns }} askin' me about the {{ noun }} for the {{ noun }}",
    "{{ adjective }} English, 800 {{ nouns }} of {{ noun }}",
    "Did a lot of {{ noun }} just to live this here {{ noun }}",
    "Started from the {{ noun }}, now {{ noun }} here",
    "I got my {{ nouns }} on you, you're everything that I see",
    "Call me Fred Flinstone cause {{ noun }} can make your {{ noun }} rock",
    "Dontcha wish your {{ noun }} was {{ adjective }} like {{ noun }}?",
    "{{ noun }} the way you movin, got me in {{ a_noun }}",
    "You wanna see some {{ noun }}? I wanna see some {{ noun }}",
    "Now watch me {{ noun }} that {{ noun }}",
    "Watch me {{ noun }}, now watch me {{ noun }}",
    "{{ adjective }} {{ noun }} gone give it to ya",
    "Pour some {{ noun }} on {{ noun }}",
    "You got the {{ nouns }} like Jagger",
    "I'm {{ adjective }} and I know it",
    "Maybe I'm going {{ adjective }}, maybe I'm going {{ adjective }}",
    "{{ noun }} wanna hug {{ noun }}? What rhymes with hug {{ noun }}?",
    "I be in the {{ noun }} cooking {{ nouns }} with my {{ noun }}, yeah",
    "I ain't got no {{ noun }}, {{ adjective }} {{ nouns }} is the only {{ noun }} that I like ",
    "I just bought {{ a_noun }}, three {{ nouns }}, that {{ noun }} {{ a_noun }}",
    "Listen up {{ nouns }}, cause {{ noun }} is it",
    "I ain't {{ adjective }}, I ain't {{ adjective }}",
    "{{ nouns }} just come and go like {{ nouns }}",
    "What you gonna do with all that {{ noun }}, all that {{ noun }} up in your {{ noun }}?",
    "California {{ nouns }}, we're {{ adjective }}",
    "Cause I ain't no hollaback {{ noun }}",
    "{{ adjective }} {{ noun }} so hot, we'll melt your popsicle",
    "{{ noun }} make me feel like I'm livin' {{ an_adjective }} {{ noun }}",
    "You're {{ adjective }} then you're {{ adjective }}, you're yes then you're no",
    "I'm all about that {{ noun }}, about that {{ noun }}, no {{ noun }}",
    "She wears {{ adjective }} {{ nouns }}, I wear {{ adjective }} {{ nouns }}",
    "She's {{ noun }} captain and I'm on the {{ nouns }}",
    "I don't like your {{ adjective }}, I think you need {{ an_adjective }} {{ noun }}",
    "He was {{ a_noun }}, she was {{ a_noun }}, can I make it any more {{ adjective }}?",
    "And I know she'll be the {{ noun }} of {{ noun }}, at least we'll both be {{ adjective }}",
    "I can't feel my {{ noun }} when I'm with {{ noun }}",
    "I think I found myself {{ a_noun }}, she's always {{ adjective }} when I need {{ noun }}",
    "Give it to me, I'm {{ adjective }}"
];
